//
//  DummyData.swift
//  Rarticle
//
//  Created by Jamal Aartsen on 14/07/2022.
//

import Foundation

class DummyData {
//    static let fakeData = {[
//        Article(description: "Het Sri Lankaanse parlement heeft het ontslag van president Gotabaya Rajapaksa vrijdag geaccepteerd. Het parlement gaat zich nu richten op 'de grondwettelijke benoeming van een nieuwe president', meldt de voorzitter.", title: "Sri Lankaans parlement accepteert ontslag gevluchte president", url: "https://www.nu.nl/buitenland/6212320/sri-lankaans-parlement-accepteert-ontslag-gevluchte-president.html", urlToImage: "https://media.nu.nl/m/b0ex2emabljm_xwd1280.jpg/sri-lankaans-parlement-accepteert-ontslag-gevluchte-president.jpg"),
//        Article(description: "Een hoekhuis aan Merelstraat in Oss is donderdagnacht rond halftwee beschoten door iemand met een vuurwapen. In een ruit zijn meerdere kogelinslagen te zien. Volgens de politie is er alleen sprake van materiële schade. Er was op het moment dat de schoten werden gelost niemand in huis aanwezig, zo laat een woordvoerder weten.", title: "Huis beschoten in Oss, meerdere kogelhulzen gevonden", url: "https://www.omroepbrabant.nl/nieuws/4118324/huis-beschoten-in-oss-meerdere-kogelhulzen-gevonden", urlToImage: "https://api.omroepbrabant.nl/img/f/1536/864/0.5/0.5/bWVkaWEvcHJvZC80MTE4MzYwLmpwZz9zdj0yMDE5LTA3LTA3JnN0PTIwMjAtMDEtMDFUMDAlM0EwMCUzQTAwWiZzZT0yMDQwLTAxLTAxVDAwJTNBMDAlM0EwMFomc3I9YiZzcD1yJnNpZz12VVlyZU0yd1QlMkZNWUdIU1BUVGNSTXJWbnEzcHN2V2RXRkdhT0s5dU10M2clM0Q="),
//        Article(description: "Wie dit weekend op vakantie gaat, moet rekening houden met grote drukte. De Europese wegen lopen vol met vakantiegangers. De ANWB verwacht veel files in Duitsland en Frankrijk en ook in België. Volgens de ANWB kunnen mensen die vandaag of morgen met de auto op vakantie gaan, het beste rond het middaguur vertrekken.", title: "Grote vakantiedrukte verwacht op wegen in Europa: vertrek niet te vroeg", url: "https://www.rtlnieuws.nl/nieuws/nederland/artikel/5321458/vakantiedrukte-europa-wegen-anwb-frankrijk-duitsland", urlToImage: "https://www.rtlnieuws.nl/sites/default/files/content/images/2022/07/16/CROPPER_ANP-372400213.jpg?itok=0JN-7u4y&width=1024&height=576&impolicy=semi_dynamic"),
//        Article(description: "Vanaf het terrein van de grootste kerncentrale van Europa zou de Russische artillerie ook beschietingen uitvoeren, aldus Petro Kotin, het hoofd van het Oekraïense staatsenergiebedrijf Energoatom gisteravond in een tv-interview. De kerncentrale van Zaporizja, een stad in het zuidoosten van Oekraïne, werd in maart door de Russen bezet. Sindsdien zou het Russische leger volgens Kotin het complex hebben veranderd in een militaire basis, en wordt de centrale gebruikt als steunpunt voor artillerie-aanvallen. Bij de meest recente Russische raketaanval in de regio kwamen drie mensen om en vielen vijftien gewonden. Nog niet duidelijk is vanaf waar die raketten werden afgeschoten. De Energoatom-directeur ondersteunde zijn uitspraken tijdens de uitzending niet met bewijzen maar zei dat ‘zwaar materieel (tanks, gepantserde voertuigen), 500 soldaten en vrachtwagens geladen met wapens en explosieven geparkeerd staan op het terrein van de energiecentrale’.", title: "‘Russen gebruiken Oekraïense kerncentrale als wapendepot en raketlanceerinstallatie’", url: "https://www.ad.nl/buitenland/russen-gebruiken-oekraiense-kerncentrale-als-wapendepot-en-raketlanceerinstallatie~ab7a19a3/?referrer=https%3A%2F%2Fwww.google.com%2F", urlToImage: "https://images0.persgroep.net/rcs/UiII-dZz0SwPz00YqJQ2Ojc9zlo/diocontent/216535632/_fill/1350/899/?appId=21791a8992982cd8da851550a453bd7f&quality=0.9")
//    ]}
}
